const MAP_FEATURES = window.JOBSIGHT_MAP_FEATURES || [];
const BOARD_DATA_URL = './data/job-board-data.json';
const SOURCE_HEALTH_URL = './data/source-health.json';
const METRO_KEYS = new Set(['BANYULE','BAYSIDE','BOROONDARA','BRIMBANK','CARDINIA','CASEY','DAREBIN','FRANKSTON','GLEN EIRA','GREATER DANDENONG','HOBSONS BAY','HUME','KINGSTON','KNOX','MANNINGHAM','MARIBYRNONG','MAROONDAH','MELBOURNE','MELTON','MERRI BEK','MONASH','MOONEE VALLEY','MOORABOOL','MORNINGTON PENINSULA','NILLUMBIK','PORT PHILLIP','STONNINGTON','WHITEHORSE','WHITTLESEA','WYNDHAM','YARRA','YARRA RANGES']);
const els = { mapPaths: document.getElementById('map-paths'), mapMarkers: document.getElementById('map-markers'), metroMap: document.getElementById('metro-map'), metroPaths: document.getElementById('metro-paths'), metroMarkers: document.getElementById('metro-markers'), tooltip: document.getElementById('map-tooltip'), search: document.getElementById('job-search'), hasSalaryToggle: document.getElementById('has-salary-toggle'), hasBandToggle: document.getElementById('has-band-toggle'), isCurrentToggle: document.getElementById('is-current-toggle'), dateRangeButtons: [...document.querySelectorAll('[data-date-range]')], list: document.getElementById('job-list'), resultCount: document.getElementById('result-count'), resultContext: document.getElementById('result-context'), snapshotNote: document.getElementById('snapshot-note'), dataStatus: document.getElementById('data-status'), selectedCouncil: document.getElementById('selected-council'), selectedCouncilLabel: document.getElementById('selected-council-label'), clearCouncil: document.getElementById('clear-council'), bandChart: document.getElementById('band-chart'), bandChartTitle: document.getElementById('band-chart-title') };
const state = { jobs: [], query: '', selectedCouncilKey: '', selectedBand: '', dateRange: 'all', referenceDate: null, health: null, hasSalaryOnly: false, hasBandOnly: false, isCurrentOnly: false, counts: new Map(), features: new Map(), metroCenter: null };
function normaliseKey(value) { return String(value || '').toUpperCase().replace(/&/g, ' AND ').replace(/[^A-Z0-9]+/g, ' ').trim().replace(/\s+/g, ' '); }
function escapeHtml(value) { return String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;'); }
function compactText(value) { return String(value ?? '').replace(/\s+/g, ' ').trim(); }
function textExcerpt(value, limit = 300) { const text = compactText(value); if (text.length <= limit) return text; const cut = text.slice(0, limit).replace(/\s+\S*$/, '').replace(/[ ,.;:]+$/, ''); return cut + '...'; }
function formatCount(value) { return Number(value || 0).toLocaleString('en-AU'); }
function formatDate(value) { if (!value) return ''; const d = new Date(value); return Number.isNaN(d.getTime()) ? String(value) : d.toLocaleDateString('en-AU', { day:'2-digit', month:'short', year:'numeric' }); }
function formatDateTime(value) { if (!value) return ''; const d = new Date(value); return Number.isNaN(d.getTime()) ? String(value) : d.toLocaleString('en-AU', { day:'2-digit', month:'short', year:'numeric', hour:'numeric', minute:'2-digit', timeZoneName:'short' }); }
function parseDateValue(value) { if (!value) return null; const text = String(value); const candidate = /^\d{4}-\d{2}$/.test(text) ? text + '-01T00:00:00Z' : text; const d = new Date(candidate); return Number.isNaN(d.getTime()) ? null : d; }
function startOfMonth(date) { return new Date(date.getFullYear(), date.getMonth(), 1); }
function addMonths(date, amount) { const next = new Date(date); next.setMonth(next.getMonth() + amount); return next; }
function dateRangeStart() { const reference = state.referenceDate || new Date(); if (state.dateRange === 'month') return startOfMonth(reference); if (state.dateRange === 'quarter') return addMonths(startOfMonth(reference), -2); return null; }
function dateRangeLabel(value = state.dateRange) { return { month:'This month', quarter:'Last 3 months', all:'All time' }[value] || 'All time'; }
function jobDate(job) { return job.jobDate || parseDateValue(job.first_seen_at || job.last_seen_at || job.observed_at || job.canonical_reference_month); }
function matchesDateRange(job) { const start = dateRangeStart(); if (!start) return true; const date = jobDate(job); return Boolean(date && date >= start); }
function moneyLabel(value) { const n = Number(value); if (!Number.isFinite(n)) return ''; return Math.abs(n - Math.round(n)) < .01 ? '$' + Math.round(n).toLocaleString('en-AU') : '$' + n.toLocaleString('en-AU', { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
function formatCompactMoney(value) { const n = Number(value); if (!Number.isFinite(n)) return ''; return Math.abs(n) >= 1000 ? '$' + Math.round(n / 1000).toLocaleString('en-AU') + 'k' : moneyLabel(n); }
function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
  function isReferenceSalary(job) { const text = compactText(job.advertised_salary_text).replace(/[\u2013\u2014]/g, '-'); const min = Number(job.advertised_salary_min); const max = Number(job.advertised_salary_max); return /^\d{1,3}-20\d{2}$/.test(text) && Number.isFinite(min) && Number.isFinite(max) && Math.min(min, max) <= 999 && Math.max(min, max) >= 2000 && Math.max(min, max) <= 2099; }
  function salaryRangeLabel(job) { if (isReferenceSalary(job)) return ''; const min = Number(job.advertised_salary_min); const max = Number(job.advertised_salary_max); const hasMin = Number.isFinite(min); const hasMax = Number.isFinite(max); if (!hasMin && !hasMax) return ''; const low = hasMin ? min : max; const high = hasMax ? max : min; const label = Math.abs(high - low) < .01 ? moneyLabel(low) : moneyLabel(low) + '-' + moneyLabel(high); return job.advertised_salary_period ? label + '/' + job.advertised_salary_period : label; }
function junkTitleRank(job) { return ['breadcrumb', 'application process', 'careers in early years'].includes(String(job.job_title || '').toLowerCase()) ? 1 : 0; }
  const NON_JOB_TITLES = new Set(['careers','careers at council','careers at yarra ranges','careers with us','breadcrumb','current opportunities','current vacancies','employment','employment opportunities','job vacancies','jobs','jobs and careers','jobs and opportunities','gtranslate','main navigation','menu','listen','about us','acknowledgement of country','alerts','apply for a job','business jobs and investment','contact us','cookie policy','employment hero work app','facebook','find a local job','help centre','hr login','instagram','linkedin','media centre','newsroom','our organisation','privacy policy','recommended for you','terms and conditions','youtube','positions vacant','work with us','working for council']);
const NON_JOB_TITLE_PATTERNS = [/\bselect this as your preferred language\b/i,/^javascript is (?:turned off|not available)/i,/^\d+\s+dismissed announcement$/i,/^search [0-9,]+ jobs? now$/i,/^(about|business workshops|business jobs|contact|cookie|data processing|employee benefits|employment resources|employment support|financial disclosure|harvest work|implementation hub|integrations|looking to invest|payday super|products|quick demos|sales|service centre|solutions|support for your business|tenders and contracts|trust and legal|upper yarra local|why work for council)\b/i,/^(canada|malaysia|new zealand|singapore|united kingdom)$/i,/^employment (hero|shouldn|intelligently)/i,/^find your next role with employment hero jobs$/i,/^region of choice$/i,/^start or grow your business$/i];
const NON_JOB_HOST_PATTERNS = [/(^|\.)facebook\.com$/i,/(^|\.)instagram\.com$/i,/(^|\.)linkedin\.com$/i,/(^|\.)tiktok\.com$/i,/(^|\.)youtube\.com$/i,/^help\.employmenthero\.com$/i,/^secure\.employmenthero\.com$/i,/^employmenthero\.page\.link$/i];
const ROLE_TITLE_RE = /\b(accountant|administrator|adviser|advisor|analyst|assistant|auditor|business partner|case manager|coordinator|crew|developer|driver|educator|engineer|facilitator|graduate|inspector|instructor|labou?rer|lead|leader|leading hand|librarian|maintenance employee|manager|nurse|officer|operator|planner|producer|project|ranger|receptionist|specialist|supervisor|surveyor|teacher|team leader|technician|trainee|worker)\b/i;
const VACANCY_CONTEXT_RE = /\b(applications? close|apply now|closing date|fixed term|full[- ]time|part[- ]time|permanent|position|responsibilities|role|salary|selection criteria|superannuation|successful applicant)\b/i;
const BAND_PATTERNS = [/\b(?:classification|classified|salary|remuneration|position)?\s*(?:band|banding|band\s*\/\s*level|level\s*\/\s*band)\s*(?:no\.?|number|level|range|grade|:|-)?\s*([1-8]|one|two|three|four|five|six|seven|eight)(?:\s*(?:\/|-|to|or)\s*(?:[1-8]|one|two|three|four|five|six|seven|eight))?[a-d]?\b/i,/\b(?:classification|classified|municipal\s+employee|local\s+government\s+employee|employee|me)\s+(?:level|grade)\s*(?:no\.?|number|:|-)?\s*([1-8]|one|two|three|four|five|six|seven|eight)[a-d]?\b/i,/\b(?:level|grade)\s*([1-8]|one|two|three|four|five|six|seven|eight)[a-d]?\b.{0,48}\b(?:municipal|local\s+government|classification|classified|award|band)\b/i];
const BAND_WORDS = { one:1, two:2, three:3, four:4, five:5, six:6, seven:7, eight:8 };
function titleKey(value) { return compactText(value).toLowerCase().replace(/&/g, ' and ').replace(/[^a-z0-9]+/g, ' ').trim(); }
function bandValue(value) { const token = compactText(value).toLowerCase(); return /^\d$/.test(token) ? Number(token) : BAND_WORDS[token] || ''; }
function bandFromText(...texts) { for (const text of texts) { const clean = compactText(text); if (!clean) continue; for (const pattern of BAND_PATTERNS) { const match = clean.match(pattern); if (match) return bandValue(match[1]); } } return ''; }
function resolveBand(job) { if (compactText(job.classification_status) === 'salary_band_conflict') return ''; const existing = Number(job.standard_band_number || job.band); if (Number.isFinite(existing) && existing >= 1 && existing <= 8) return existing; return bandFromText(job.classification_band, job.evidence?.band_text, job.job_title || job.title, job.advertised_salary_text, job.description_text || job.description_excerpt, job.closing_at_text || job.closing_text, job.location_text, job.work_type); }
function classificationWithBand(status, band) { const value = compactText(status) || 'unclassified'; return band && ['unclassified','description_only','salary_only','parse_warning'].includes(value) ? 'explicit_band' : value; }
function roleTitleSignal(job) { return ROLE_TITLE_RE.test(compactText(job.job_title || job.title)); }
function vacancyContextSignal(job) { return VACANCY_CONTEXT_RE.test([job.description_text, job.description_excerpt, job.closing_at_text, job.closing_text, job.work_type].map(compactText).join(' ')); }
function hasUsefulVacancySignal(job) { const band = resolveBand(job); const salary = Boolean(salaryRangeLabel(job) || compactText(job.advertised_salary_text)); const closing = Boolean(compactText(job.closing_at || job.closing_at_text || job.closing_date || job.closing_text)); const locationOrWork = Boolean(compactText(job.location_text) || compactText(job.work_type)); const role = roleTitleSignal(job); const context = vacancyContextSignal(job); return Boolean(band || role && (salary || closing || locationOrWork || context)); }
function hasVacancySignal(job) { return hasUsefulVacancySignal(job) || Boolean(compactText(job.location_text) || compactText(job.work_type) || compactText(job.closing_at || job.closing_at_text)); }
function isGenericJobShell(job) { const title = titleKey(job.job_title || job.title); if (!title) return true; if (NON_JOB_TITLES.has(title)) return true; if (NON_JOB_TITLE_PATTERNS.some(pattern => pattern.test(title))) return true; if (/^careers?( at| with|$)/.test(title)) return true; if (/^(current )?(job )?vacanc(y|ies)$/.test(title)) return true; if (/jobs? (and|or) (careers|opportunities)/.test(title)) return true; return false; }
function isNonJobUrl(url) { try { const parsed = new URL(url); const host = parsed.hostname.replace(/^www\./, ''); if ((host === 'au.jora.com' || host === 'jora.com') && parsed.pathname.replace(/\/+$/, '') === '') return true; return NON_JOB_HOST_PATTERNS.some(pattern => pattern.test(host)); } catch { return false; } }
function isLikelyVacancy(job) { const key = job.council_key || job.councilKey; if (!job.job_title || !job.job_url || !key) return false; if (isGenericJobShell(job) || isNonJobUrl(job.job_url)) return false; const status = compactText(job.classification_status).toLowerCase().replace(/\s+/g, '_'); if (['parse_warning','parser_warning','unclassified','description_only'].includes(status) && !hasUsefulVacancySignal(job)) return false; if (!hasUsefulVacancySignal(job) && !roleTitleSignal(job)) return false; return true; }
function canonicalUrlPath(url) { try { const parsed = new URL(url); return (parsed.hostname.replace(/^www\./, '') + parsed.pathname.replace(/\/+$/, '')).toLowerCase(); } catch { return compactText(url).split('?')[0].toLowerCase(); } }
function vacancyDedupeKey(job) { return [job.council_key || job.councilKey, titleKey(job.job_title), canonicalUrlPath(job.job_url), compactText(job.location_text).toLowerCase(), compactText(job.work_type).toLowerCase(), compactText(job.closing_at || job.closing_at_text).toLowerCase(), (salaryRangeLabel(job) || compactText(job.advertised_salary_text)).toLowerCase()].join('|'); }
function dedupeJobs(jobs) { const seen = new Set(); return jobs.filter(job => { const key = vacancyDedupeKey(job); if (seen.has(key)) return false; seen.add(key); return true; }); }
function classificationLabel(value) { return { description_only:'Description signal', explicit_band:'Explicit band', parse_warning:'Parser warning', salary_band_conflict:'Salary conflict', salary_only:'Salary signal', unclassified:'Unclassified' }[value] || String(value || 'Unclassified').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()); }
function sourceLabel(value) { return String(value || 'Council website').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()); }
function externalHost(url) { try { return new URL(url).hostname.replace(/^www\./, ''); } catch { return ''; } }
function inlineBoardData() { const node = document.getElementById('jobsight-board-data'); const text = node ? compactText(node.textContent) : ''; if (!text) return null; return JSON.parse(text); }
function validateBoardData(data) { if (!data || data.schema_version !== 'jobsight.board.v1' || !Array.isArray(data.jobs)) throw new Error('Public board dataset is missing or invalid.'); return data; }
async function loadJson(url) { const response = await fetch(url, { cache: 'no-store' }); if (!response.ok) throw new Error(url + ' returned ' + response.status); return response.json(); }
async function loadBoardData() { const embedded = inlineBoardData() || window.JOBSIGHT_BOARD_DATA; if (embedded) return validateBoardData(embedded); try { return validateBoardData(await loadJson(BOARD_DATA_URL)); } catch (error) { const fallback = inlineBoardData() || window.JOBSIGHT_BOARD_DATA; if (fallback) return validateBoardData(fallback); throw error; } }
async function loadHealthData() { try { return await loadJson(SOURCE_HEALTH_URL); } catch { return null; } }
function healthSummaryText(health) { const summary = health?.summary || {}; if (!health) return 'Health report pending'; const degraded = Number(summary.degraded || 0); const failed = Number(summary.failed || 0); const fallback = Number(summary.fallback_used || 0); const ok = Number(summary.ok || 0); const quarantined = Number(summary.quarantined_rows || 0); if (degraded || failed || fallback) return `${ok} sources ok, ${degraded} degraded, ${failed} failed, ${fallback} using fallback, ${quarantined} quarantined rows`; return `${ok} sources ok, ${quarantined} quarantined rows`; }
function renderDataStatus(data, health) { if (!els.dataStatus) return; const updated = data.saved_at || data.summary?.generated_at || health?.generated_at; const summary = health?.summary || {}; const warning = Boolean(Number(summary.degraded || 0) || Number(summary.failed || 0) || Number(summary.fallback_used || 0)); els.dataStatus.classList.toggle('is-warning', warning); els.dataStatus.innerHTML = `<strong>${warning ? 'Daily refresh degraded' : 'Daily refresh active'}</strong><span>${escapeHtml(updated ? 'Last successful refresh ' + formatDateTime(updated) : 'Refresh time not listed')}</span><span>${escapeHtml(healthSummaryText(health))}</span>`; }
function enrichJob(job) { const key = normaliseKey(job.council_key || job.short_name || job.council_name); const band = resolveBand(job) || ''; const status = classificationWithBand(job.classification_status, band); const salary = job.advertised_salary_text || salaryRangeLabel(job); const seenDate = parseDateValue(job.first_seen_at || job.last_seen_at || job.observed_at || job.canonical_reference_month); const seenLabel = formatDate(job.first_seen_at || job.last_seen_at || job.observed_at || job.canonical_reference_month); const searchText = [job.job_title, job.council_name, job.short_name, key, band ? 'band ' + band : '', salary, job.location_text, job.work_type, seenLabel, job.source_family, classificationLabel(status)].filter(Boolean).join(' ').toLowerCase(); return { ...job, councilKey: key, standard_band_number: band, classification_status: status, displayCouncil: job.short_name || job.council_name || key, bandLabel: band ? 'Band ' + band : classificationLabel(status), salaryLabel: salary, closingDate: formatDate(job.closing_at || job.closing_at_text), jobDate: seenDate, jobDateLabel: seenLabel, searchText }; }
function mapFilterDefs() { return '<defs><filter id="job-glow" x="-40%" y="-40%" width="180%" height="180%"><feGaussianBlur stdDeviation="4" result="blur"></feGaussianBlur><feColorMatrix in="blur" type="matrix" values="0 0 0 0 0.08 0 0 0 0 0.70 0 0 0 0 0.74 0 0 0 0.75 0"></feColorMatrix><feMerge><feMergeNode></feMergeNode><feMergeNode in="SourceGraphic"></feMergeNode></feMerge></filter><filter id="selected-glow" x="-55%" y="-55%" width="210%" height="210%"><feGaussianBlur stdDeviation="6.5" result="blur"></feGaussianBlur><feColorMatrix in="blur" type="matrix" values="0 0 0 0 1 0 0 0 0 0.78 0 0 0 0 0.30 0 0 0 1 0"></feColorMatrix><feMerge><feMergeNode></feMergeNode><feMergeNode in="SourceGraphic"></feMergeNode></feMerge></filter></defs>'; }
function lgaNameLabelHtml(feature, isMetro = false) {
  const fullName = compactText(feature.n);
  const cleaned = fullName.replace(/\s+(?:City Council|City|Shire Council|Shire|Borough|Rural City Council|Rural City|Council)$/i, '');
  const limit = isMetro ? 18 : 22;
  const label = cleaned.length > limit ? cleaned.slice(0, limit - 1).trim() + '...' : cleaned;
  const markerClass = `lga-name-marker${isMetro ? ' metro-lga-name-marker' : ''}`;
  const textClass = `lga-name-label${isMetro ? ' metro-lga-name-label' : ''}`;
  return `<g class="${markerClass}" data-key="${escapeHtml(feature.k)}" transform="translate(${feature.x} ${feature.y})"><text class="${textClass}" data-key="${escapeHtml(feature.k)}" x="0" y="0">${escapeHtml(label)}</text></g>`;
}
function updateMapLabelState(counts) {
  document.querySelectorAll('.lga-name-label').forEach(label => {
    const key = label.dataset.key;
    const count = counts.get(key) || 0;
    label.classList.toggle('has-jobs', count > 0);
    label.classList.toggle('is-selected', state.selectedCouncilKey === key);
    label.classList.toggle('is-dimmed', Boolean(state.selectedCouncilKey && state.selectedCouncilKey !== key) || Boolean(count === 0 && (state.query.trim() || state.selectedBand || state.hasSalaryOnly || state.hasBandOnly || state.isCurrentOnly || state.dateRange !== 'all')));
  });
}
function renderMapBase() {
  els.mapPaths.innerHTML = mapFilterDefs() + MAP_FEATURES.map(f => `<path class="lga-boundary${METRO_KEYS.has(f.k) ? ' is-metro-main' : ''}" data-key="${escapeHtml(f.k)}" d="${f.d}"><title>${escapeHtml(f.n)}</title></path>`).join('') + `<g class="lga-name-layer">${MAP_FEATURES.filter(f => !METRO_KEYS.has(f.k)).map(f => lgaNameLabelHtml(f)).join('')}</g>`;
  for (const feature of MAP_FEATURES) state.features.set(feature.k, feature);
  const metro = MAP_FEATURES.filter(f => METRO_KEYS.has(f.k));
  const minX = Math.min(...metro.map(f => f.b[0]));
  const minY = Math.min(...metro.map(f => f.b[1]));
  const maxX = Math.max(...metro.map(f => f.b[2]));
  const maxY = Math.max(...metro.map(f => f.b[3]));
  const metroZoom = 1.804;
  const viewWidth = (maxX - minX) / metroZoom;
  const viewHeight = (maxY - minY) / metroZoom;
  const centerX = (minX + maxX) / 2;
  const centerY = (minY + maxY) / 2 - viewHeight * 0.15;
  els.metroMap.setAttribute('viewBox', `${centerX - viewWidth / 2} ${centerY - viewHeight / 2} ${viewWidth} ${viewHeight}`);
  state.metroCenter = { x: centerX, y: centerY + viewHeight * 0.05 };
  els.metroPaths.innerHTML = mapFilterDefs() + `<g class="metro-static-shape">${metro.map(f => `<path class="metro-static-boundary" d="${f.d}"><title>${escapeHtml(f.n)}</title></path>`).join('')}</g>`;
  document.querySelectorAll('#map-paths .lga-boundary').forEach(path => {
    path.addEventListener('mousemove', event => showTooltip(event, path.dataset.key));
    path.addEventListener('mouseleave', hideTooltip);
    path.addEventListener('click', () => selectCouncil(path.dataset.key));
  });
}
function hasBand(job) { const band = Number(job.standard_band_number); return Number.isFinite(band) && band >= 1 && band <= 8; }
function hasSalary(job) { return Boolean(advertisedAnnualRange(job) || compactText(job.advertised_salary_text || job.salaryLabel)); }
function isCurrent(job) { return compactText(job.observed_status).toLowerCase() === 'seen_latest_run'; }
function jobsMatchingSearch(jobs) { const query = state.query.trim().toLowerCase(); return jobs.filter(job => matchesDateRange(job) && (!query || job.searchText.includes(query)) && (!state.selectedBand || String(job.standard_band_number || '') === state.selectedBand) && (!state.hasSalaryOnly || hasSalary(job)) && (!state.hasBandOnly || hasBand(job)) && (!state.isCurrentOnly || isCurrent(job))); }
function visibleJobs() { const filtered = jobsMatchingSearch(state.jobs); return state.selectedCouncilKey ? filtered.filter(job => job.councilKey === state.selectedCouncilKey) : filtered; }
function countByCouncil(jobs) { const counts = new Map(); for (const job of jobs) counts.set(job.councilKey, (counts.get(job.councilKey) || 0) + 1); return counts; }
function quantile(values, q) { const ordered = values.filter(Number.isFinite).sort((a, b) => a - b); if (!ordered.length) return 0; return ordered[Math.min(ordered.length - 1, Math.floor((ordered.length - 1) * q))]; }
function jobColour(count, domain) { const scale = clamp(count / Math.max(1, domain), 0.08, 1); return { scale, fillAlpha: 0.12 + scale * 0.24, strokeAlpha: 0.34 + scale * 0.52, rgb: [24, 181, 178], strokeRgb: [114, 232, 220] }; }
function applyJobColour(element, count, domain) { const colour = jobColour(count, domain); element.style.setProperty('--job-scale', colour.scale.toFixed(3)); element.style.setProperty('--job-fill-alpha', colour.fillAlpha.toFixed(3)); element.style.setProperty('--job-stroke-alpha', colour.strokeAlpha.toFixed(3)); element.style.setProperty('--job-r', String(colour.rgb[0])); element.style.setProperty('--job-g', String(colour.rgb[1])); element.style.setProperty('--job-b', String(colour.rgb[2])); element.style.setProperty('--job-stroke-r', String(colour.strokeRgb[0])); element.style.setProperty('--job-stroke-g', String(colour.strokeRgb[1])); element.style.setProperty('--job-stroke-b', String(colour.strokeRgb[2])); }
function markerHtmlFor(key, count, isMetro = false) { const f = state.features.get(key); if (!f || !count) return ''; const r = isMetro ? Math.max(1.75, Math.min(2.85, 1.85 + Math.sqrt(count) * 0.36)) : Math.max(6.5, Math.min(15, 6 + Math.sqrt(count) * 2.45)); return `<g class="count-marker${isMetro ? ' metro-count-marker' : ''} is-visible" data-key="${escapeHtml(key)}" transform="translate(${f.x} ${f.y})"><circle r="${r}"></circle><text class="count-value">${count}</text><text class="count-label" y="${r + 12}">${escapeHtml(f.n)}</text></g>`; }
function metroAggregateMarkerHtml(count) { if (!state.metroCenter || !count) return ''; const r = Math.max(9, Math.min(18, 7 + Math.sqrt(count) * 0.72)); return `<g class="count-marker metro-aggregate-marker is-visible" transform="translate(${state.metroCenter.x} ${state.metroCenter.y})" aria-label="Metro councils ${formatCount(count)} jobs"><circle r="${r}"></circle><text class="count-value">${formatCount(count)}</text><text class="count-label" y="${r + 10}">Metro total</text></g>`; }
function wireMapMarkers(countDomain) { document.querySelectorAll('.count-marker[data-key]').forEach(marker => { const key = marker.dataset.key; const count = state.counts.get(key) || 0; applyJobColour(marker, count, countDomain); marker.classList.toggle('is-selected', state.selectedCouncilKey === key); marker.addEventListener('mousemove', event => showTooltip(event, key)); marker.addEventListener('mouseleave', hideTooltip); marker.addEventListener('click', () => selectCouncil(key)); }); }
function updateMap(filteredJobs) {
  state.counts = countByCouncil(filteredJobs);
  const maxCount = Math.max(1, ...state.counts.values());
  const countDomain = Math.max(2, quantile([...state.counts.values()], 0.9));
  const hasFilter = Boolean(state.query.trim() || state.selectedBand || state.hasSalaryOnly || state.hasBandOnly || state.isCurrentOnly || state.dateRange !== 'all' || state.selectedCouncilKey);
  document.querySelectorAll('.lga-boundary').forEach(path => {
    const key = path.dataset.key;
    const count = state.counts.get(key) || 0;
    applyJobColour(path, count, countDomain);
    path.classList.toggle('has-jobs', count > 0);
    path.classList.toggle('is-heavy', count >= Math.max(4, maxCount * 0.5));
    path.classList.toggle('is-selected', state.selectedCouncilKey === key);
    path.classList.toggle('is-dimmed', hasFilter && count === 0 || Boolean(state.selectedCouncilKey && state.selectedCouncilKey !== key));
    path.classList.toggle('is-dim', path.classList.contains('is-dimmed'));
  });
  updateMapLabelState(state.counts);
  els.mapMarkers.innerHTML = [...state.counts].filter(([, count]) => count > 0).map(([key, count]) => markerHtmlFor(key, count)).join('');
  const metroTotal = [...state.counts].reduce((total, [key, count]) => total + (METRO_KEYS.has(key) ? count : 0), 0);
  const metroDomain = Math.max(countDomain, metroTotal || 1);
  document.querySelectorAll('.metro-static-boundary').forEach(path => {
    applyJobColour(path, metroTotal, metroDomain);
    path.classList.toggle('has-jobs', metroTotal > 0);
    path.classList.toggle('is-dimmed', hasFilter && metroTotal === 0);
  });
  els.metroMarkers.innerHTML = metroAggregateMarkerHtml(metroTotal);
  const metroMarker = els.metroMarkers.querySelector('.metro-aggregate-marker');
  if (metroMarker) applyJobColour(metroMarker, metroTotal, metroDomain);
  wireMapMarkers(countDomain);
}
function showTooltip(event, key) { const feature = state.features.get(key); const count = state.counts.get(key) || countByCouncil(state.jobs).get(key) || 0; els.tooltip.innerHTML = `<strong>${escapeHtml(feature?.n || key)}</strong><br>${formatCount(count)} job${count === 1 ? '' : 's'}`; els.tooltip.style.left = event.clientX + 'px'; els.tooltip.style.top = event.clientY + 'px'; els.tooltip.classList.add('is-visible'); els.tooltip.setAttribute('aria-hidden', 'false'); }
function hideTooltip() { els.tooltip.classList.remove('is-visible'); els.tooltip.setAttribute('aria-hidden', 'true'); }
function selectCouncil(key) { if (!key || !countByCouncil(jobsMatchingSearch(state.jobs)).has(key)) return; state.selectedCouncilKey = key; hideTooltip(); render(); }
window.JOBSIGHT_SELECT_COUNCIL = selectCouncil;
function firstFinite(values) { for (const value of values) { const number = Number(value); if (Number.isFinite(number)) return number; } return null; }
function advertisedAnnualRange(job) { const min = firstFinite([job.advertised_salary_min]); const max = firstFinite([job.advertised_salary_max, job.advertised_salary_min]); if (min === null && max === null) return null; const low = Math.min(min ?? max, max ?? min); const high = Math.max(min ?? max, max ?? min); const period = String(job.advertised_salary_period || '').toLowerCase(); const looksAnnual = !period || ['year', 'annual', 'annum', 'pa', 'p.a.', 'per annum'].includes(period) || high >= 30000; if (!looksAnnual || high < 30000) return null; return { low: low < 30000 ? high : low, high }; }
function stableUnit(value) { let hash = 2166136261; const text = String(value || ''); for (let index = 0; index < text.length; index += 1) { hash ^= text.charCodeAt(index); hash = Math.imul(hash, 16777619); } return ((hash >>> 0) % 10000) / 10000; }
function salaryEvidence(job) { const range = advertisedAnnualRange(job); const band = Number(job.standard_band_number); if (!range || !Number.isFinite(band) || band < 1 || band > 8) return null; return { job, band, low: Math.min(range.low, range.high), high: Math.max(range.low, range.high), midpoint: (range.low + range.high) / 2, jitter: stableUnit(job.job_uid || `${job.displayCouncil}-${job.job_title}`) }; }
function salaryPercent(value, min, max) { if (max <= min) return 50; return clamp(((value - min) / (max - min)) * 100, 1.5, 98.5); }
function salaryMinimumAxisDomain(points) { if (!points.length) return { min: 0, max: 1 }; let minSalary = Math.min(...points.map(point => point.low)); let maxSalary = Math.max(...points.map(point => point.low)); minSalary = Math.floor(minSalary / 10000) * 10000; maxSalary = Math.ceil(maxSalary / 10000) * 10000; if (maxSalary - minSalary < 20000) { minSalary -= 10000; maxSalary += 10000; } return { min: minSalary, max: maxSalary }; }
function salaryLaneY(point) { return clamp(50 + (point.jitter - 0.5) * 54, 18, 82); }
function averageSalary(values) { const numbers = values.filter(Number.isFinite); if (!numbers.length) return null; return numbers.reduce((total, value) => total + value, 0) / numbers.length; }
function salaryMinimumBandLabel(points) { if (!points.length) return 'no annual salary'; const low = Math.min(...points.map(point => point.low)); const high = Math.max(...points.map(point => point.low)); return Math.abs(high - low) < 1 ? formatCompactMoney(high) : 'min ' + formatCompactMoney(low) + '-' + formatCompactMoney(high); }
function salaryMinimumPointTitle(point) { return `${point.job.displayCouncil}: ${point.job.job_title} - Band ${point.band} - minimum ${moneyLabel(point.low)}/year`; }
function renderBandChart(filteredJobs) { const bandedJobs = filteredJobs.filter(hasBand); const counts = new Map(); for (const job of bandedJobs) { const band = String(job.standard_band_number || ''); if (band) counts.set(band, (counts.get(band) || 0) + 1); } const points = bandedJobs.map(salaryEvidence).filter(Boolean); const max = Math.max(1, ...counts.values()); const salaryDomain = salaryMinimumAxisDomain(points); els.bandChartTitle.textContent = formatCount(bandedJobs.length) + ' banded job' + (bandedJobs.length === 1 ? '' : 's'); const axis = `<div class="band-pay-axis"><span>${points.length ? formatCompactMoney(salaryDomain.min) : 'No salary'}</span><span>${points.length ? 'advertised annual minimum' : 'count only'}</span><span>${points.length ? formatCompactMoney(salaryDomain.max) : 'signal'}</span></div>`; const rows = Array.from({ length: 8 }, (_, index) => { const band = String(index + 1); const count = counts.get(band) || 0; const bandPoints = points.filter(point => String(point.band) === band); const averageMin = averageSalary(bandPoints.map(point => point.low)); const averageMarker = averageMin ? `<span class="band-pay-average" style="--avg-x:${salaryPercent(averageMin, salaryDomain.min, salaryDomain.max).toFixed(2)}%" title="Average minimum ${escapeHtml(moneyLabel(averageMin))}/year"><i></i><b>${escapeHtml(formatCompactMoney(averageMin))}</b></span>` : ''; const dots = bandPoints.map(point => `<span class="salary-dot" style="--x:${salaryPercent(point.low, salaryDomain.min, salaryDomain.max).toFixed(2)}%;--y:${salaryLaneY(point).toFixed(2)}%" title="${escapeHtml(salaryMinimumPointTitle(point))}"></span>`).join(''); const active = state.selectedBand === band; return `<div class="band-pay-row${active ? ' is-active' : ''}${count ? '' : ' is-empty'}" style="--density:${((count / max) * 100).toFixed(2)}%" data-band="${band}" role="button" tabindex="0" aria-pressed="${active ? 'true' : 'false'}"><div class="band-pay-label"><span>Band ${band}</span><strong>${formatCount(count)}</strong><small>${salaryMinimumBandLabel(bandPoints)}</small></div><div class="band-pay-lane"><i class="band-pay-density"></i>${averageMarker}${dots}</div></div>`; }).join(''); els.bandChart.innerHTML = axis + rows; els.bandChart.querySelectorAll('.band-pay-row').forEach(row => row.addEventListener('click', () => { state.selectedBand = state.selectedBand === row.dataset.band ? '' : row.dataset.band; render(); })); }
function renderJobs(jobs) { if (!jobs.length) { els.list.innerHTML = '<div class="empty-note">No jobs match the current filters.</div>'; return; } els.list.innerHTML = jobs.map(job => { const details = [['Council', job.council_name || job.displayCouncil], ['Signal', classificationLabel(job.classification_status)], ['Salary', job.salaryLabel || 'Not listed'], ['Location', job.location_text || 'Not listed'], ['Work type', job.work_type || 'Not listed'], ['Source', sourceLabel(job.source_family)], ['Job date', job.jobDateLabel || 'Not listed'], ['Seen', [formatDate(job.first_seen_at), formatDate(job.last_seen_at)].filter(Boolean).join(' to ') || 'Not listed']]; const host = externalHost(job.job_url); return `<article class="job-card"><div class="job-meta"><span>${escapeHtml(job.displayCouncil)}</span><span>${escapeHtml(job.bandLabel)}</span>${job.closingDate ? `<span>Closes ${escapeHtml(job.closingDate)}</span>` : ''}</div><h2>${escapeHtml(job.job_title)}</h2>${job.description_text ? `<p>${escapeHtml(job.description_text)}</p>` : ''}<dl class="job-details">${details.map(([label, value]) => `<div><dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}</dd></div>`).join('')}</dl><a class="external-link" href="${escapeHtml(job.job_url)}" target="_blank" rel="noopener noreferrer">View external listing${host ? ' ' + escapeHtml(host) : ''}</a></article>`; }).join(''); }
function renderDateControls() { els.dateRangeButtons.forEach(button => { const active = button.dataset.dateRange === state.dateRange; button.classList.toggle('is-active', active); button.setAttribute('aria-pressed', active ? 'true' : 'false'); }); }
function render() { renderDateControls(); const allFiltered = jobsMatchingSearch(state.jobs); const shown = visibleJobs(); const chartJobs = state.selectedCouncilKey ? shown : allFiltered; const lgaCount = countByCouncil(shown).size; updateMap(allFiltered); renderBandChart(chartJobs); renderJobs(shown); els.resultCount.textContent = `${formatCount(shown.length)} job${shown.length === 1 ? '' : 's'}`; const contextParts = [`${formatCount(lgaCount)} council area${lgaCount === 1 ? '' : 's'} highlighted`, dateRangeLabel()]; if (state.isCurrentOnly) contextParts.push('Current only'); if (state.selectedBand) contextParts.push('Band ' + state.selectedBand); els.resultContext.textContent = contextParts.join(' - '); const selected = state.selectedCouncilKey ? state.features.get(state.selectedCouncilKey) : null; els.selectedCouncil.hidden = !selected; els.clearCouncil.disabled = !selected; els.selectedCouncilLabel.textContent = selected ? `${selected.n} selected` : ''; }
async function init() { try { renderMapBase(); const [data, health] = await Promise.all([loadBoardData(), loadHealthData()]); state.health = health; state.referenceDate = parseDateValue(data.saved_at || data.summary?.generated_at || health?.generated_at) || new Date(); renderDataStatus(data, health); state.jobs = dedupeJobs((data.jobs || []).map(enrichJob).filter(isLikelyVacancy)).sort((a, b) => junkTitleRank(a) - junkTitleRank(b) || a.displayCouncil.localeCompare(b.displayCouncil) || a.job_title.localeCompare(b.job_title)); const updated = data.saved_at || data.summary?.generated_at; const councils = countByCouncil(state.jobs).size; els.snapshotNote.textContent = `${updated ? 'Updated ' + formatDate(updated) + '. ' : ''}${formatCount(state.jobs.length)} jobs in the report across ${formatCount(councils)} councils.`; render(); } catch (error) { els.snapshotNote.textContent = 'Vacancy data could not be loaded.'; if (els.dataStatus) els.dataStatus.textContent = 'Refresh status unavailable.'; els.resultCount.textContent = 'Data unavailable'; els.resultContext.textContent = error.message; els.list.innerHTML = `<div class="empty-note">${escapeHtml(error.message)}</div>`; } }
els.search.addEventListener('input', event => { state.query = event.target.value; render(); });
els.hasSalaryToggle.addEventListener('change', event => { state.hasSalaryOnly = event.target.checked; render(); });
els.hasBandToggle.addEventListener('change', event => { state.hasBandOnly = event.target.checked; render(); });
els.isCurrentToggle.addEventListener('change', event => { state.isCurrentOnly = event.target.checked; render(); });
els.dateRangeButtons.forEach(button => button.addEventListener('click', event => { event.preventDefault(); state.dateRange = button.dataset.dateRange || 'all'; render(); }));
els.clearCouncil.addEventListener('click', event => { event.preventDefault(); state.selectedCouncilKey = ''; hideTooltip(); render(); });
init();
